version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./:/docker-entrypoint-initdb.d
    restart: always
    container_name: db
