version: '3'
services:
  db:
    image: postgres:10.2
    networks:
      - database
    ports:
      - "5432:5432"
    env_file:
      - ./db/.env
    restart: always
    container_name: db
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    networks:
      - database
    ports:
      - 8000:8000
      - 8001:8001
    depends_on:
      - db
    restart: always
    container_name: back
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    depends_on:
      - back
    ports:
      - 3000:3000
    restart: always
    container_name: front

networks:
  database:
    driver: bridge
